[package]
name = "user-service"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
